---
- name: Provision BGP configuration
  hosts: juniper
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no
  environment:
    PATH: "/root/provision-EVPN-VXLAN/bin"

  vars:
    config_file: configs/{{ inventory_hostname }}.conf
    diffs_file: configs/{{ inventory_hostname }}.diff
    initial: true

  tasks:
   - name: Generate config
     template:
       src: templates/bgp.j2
       dest: "{{ config_file }}"

   - name: Load config on the device
     juniper_junos_config:
       host: "{{ junos_host }}"
       port: "{{ netconf_port }}"
       user: "{{ junos_username }}"
       passwd: "{{ junos_passwd }}"
       timeout: 60
       logfile: /tmp/ansible.changes.log
       load: merge
       commit: true
       src: "{{ config_file }}"
       diffs_file: "{{ diffs_file }}"
     register: result

   - name: Print diff
     debug: var=result.diff_lines
     when: result.diff_lines is defined

