bgp:
  groups:
    - name: fabric
      type: external
      neighbors:
        - address: 172.16.1.9
          peer_as: 65001
        - address: 172.16.1.21
          peer_as: 65002
      multipath:
        multiple_as: true
      local_as: 65004
      export_policy: export-directs;

    - name: overlay
      type: internal
      local_address: 192.168.100.12
      family: evpn
      neighbors:
        - address: 192.168.100.1
        - address: 192.168.100.2
routing_options:
  router_id: 192.168.100.12
  autonomous_system: 65000

